spring:
  application:
    name: RTask
  datasource:
    url: jdbc:h2:mem:rtaskdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
server:
  port: 8321
